/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.agenda;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int btnCancelar=0x7f050007;
        public static final int btnNovo=0x7f05000a;
        public static final int btnSalvar=0x7f050006;
        public static final int lblEndereco=0x7f050002;
        public static final int lblNome=0x7f050000;
        public static final int lblTelefone=0x7f050001;
        public static final int listaContatos=0x7f050009;
        public static final int textView1=0x7f050008;
        public static final int txtEndereco=0x7f050005;
        public static final int txtNome=0x7f050003;
        public static final int txtTelefone=0x7f050004;
    }
    public static final class layout {
        public static final int cadastro=0x7f030000;
        public static final int main=0x7f030001;
    }
    public static final class string {
        public static final int ContextoDados_onCreate=0x7f040002;
        public static final int ContextoDados_onUpgrade=0x7f040003;
        public static final int app_name=0x7f040001;
        public static final int btnCancelar=0x7f040009;
        public static final int btnSalvar=0x7f040008;
        public static final int contatos=0x7f040004;
        public static final int hello=0x7f040000;
        public static final int lblEndereco=0x7f040007;
        public static final int lblNome=0x7f040005;
        public static final int lblTelefone=0x7f040006;
    }
}
